# Generated by Django 3.1.1 on 2021-10-24 08:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proxies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proxy', models.CharField(max_length=100)),
                ('isUsed', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Proxies',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=25)),
                ('proxy', models.CharField(max_length=40, null=True)),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='Folders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentFolder_id', models.IntegerField(default=0)),
                ('foldername', models.CharField(max_length=25)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ra.user')),
            ],
            options={
                'db_table': 'Folders',
            },
        ),
        migrations.CreateModel(
            name='Bookmarks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siteName', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=500)),
                ('link', models.CharField(max_length=2000)),
                ('dateAdded', models.DateField(default=datetime.datetime(2021, 10, 24, 16, 11, 9, 741953))),
                ('isRemoved', models.BooleanField(default=False)),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ra.folders')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ra.user')),
            ],
            options={
                'db_table': 'Bookmarks',
            },
        ),
    ]
