# Generated by Django 3.2.6 on 2021-11-07 12:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ra', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmarks',
            name='isFavorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bookmarks',
            name='dateAccessed',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 7, 20, 22, 1, 349399)),
        ),
        migrations.AlterField(
            model_name='bookmarks',
            name='dateAdded',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 7, 20, 22, 1, 349399)),
        ),
        migrations.AlterField(
            model_name='practice',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 7, 20, 22, 1, 350410)),
        ),
    ]
