# Generated by Django 3.2.6 on 2021-11-15 11:42

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ra', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmarks',
            name='isFavorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bookmarks',
            name='dateAccessed',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 15, 19, 42, 8, 475895)),
        ),
        migrations.AlterField(
            model_name='bookmarks',
            name='dateAdded',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 15, 19, 42, 8, 475895)),
        ),
        migrations.AlterField(
            model_name='folders',
            name='parentFolder_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='practice',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 15, 19, 42, 8, 477910)),
        ),
        migrations.CreateModel(
            name='Bookmark_folders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookmark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ra.bookmarks')),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ra.folders')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Bookmark_folders',
            },
        ),
    ]
