# Generated by Django 3.1.3 on 2021-10-27 03:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ra', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmarks',
            name='dateAdded',
            field=models.DateField(default=datetime.datetime(2021, 10, 27, 11, 15, 37, 667532)),
        ),
    ]
