# Generated by Django 3.2.6 on 2021-11-19 15:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ra', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 19, 23, 57, 33, 517496)),
        ),
        migrations.AlterField(
            model_name='group_bookmarks',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 19, 23, 57, 33, 518508)),
        ),
        migrations.AlterField(
            model_name='practice',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 19, 23, 57, 33, 520509)),
        ),
        migrations.AlterField(
            model_name='site',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 19, 23, 57, 33, 519507)),
        ),
        migrations.AlterField(
            model_name='user_access',
            name='date_of_access',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 19, 23, 57, 33, 519507)),
        ),
        migrations.AlterField(
            model_name='user_bookmark',
            name='dateAccessed',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 19, 23, 57, 33, 515508)),
        ),
        migrations.AlterField(
            model_name='user_bookmark',
            name='dateAdded',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 19, 23, 57, 33, 515508)),
        ),
        migrations.AlterField(
            model_name='user_folder',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 19, 23, 57, 33, 518508)),
        ),
    ]
