# Generated by Django 3.2.8 on 2022-01-23 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ra', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('filename', models.CharField(max_length=100)),
                ('line_number', models.CharField(max_length=100)),
                ('site', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('search_keyword', models.CharField(max_length=400)),
            ],
        ),
    ]
