# Generated by Django 3.1.3 on 2020-12-13 08:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ra', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citations',
            name='pubdate',
            field=models.DateField(default=datetime.datetime(2020, 12, 13, 16, 52, 56, 660333)),
        ),
    ]
