# Generated by Django 3.1.1 on 2021-10-22 07:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ra', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmarks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=500)),
                ('dateAdded', models.DateField(default=datetime.datetime(2021, 10, 22, 15, 41, 51, 469289))),
                ('isRemoved', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Bookmarks',
            },
        ),
        migrations.CreateModel(
            name='Proxies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proxy', models.CharField(max_length=100)),
                ('isUsed', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'Proxies',
            },
        ),
        migrations.DeleteModel(
            name='Citations',
        ),
        migrations.AddField(
            model_name='articles',
            name='date_uploaded',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='folders',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ra.user'),
        ),
        migrations.AddField(
            model_name='user',
            name='proxy',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='bookmarks',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User', to='ra.user'),
        ),
    ]
