# Generated by Django 3.1.1 on 2021-08-12 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ra', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Citations',
        ),
        migrations.AddField(
            model_name='articles',
            name='date_uploaded',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='folders',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ra.user'),
        ),
        migrations.AddField(
            model_name='user',
            name='proxy',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
