# Generated by Django 3.1.1 on 2021-10-28 08:58

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ra', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmarks',
            name='dateAdded',
            field=models.DateField(default=datetime.datetime(2021, 10, 28, 16, 58, 36, 789018)),
        ),
        migrations.AlterField(
            model_name='bookmarks',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='folders',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
