# Generated by Django 3.2.8 on 2021-12-12 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ra', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_group',
            new_name='Group',
        ),
        migrations.AlterModelTable(
            name='group',
            table='Group',
        ),
    ]
