# Generated by Django 3.2.9 on 2021-12-01 02:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ra', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark_folder',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 1, 10, 51, 12, 162053)),
        ),
        migrations.AlterField(
            model_name='folder',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 1, 10, 51, 12, 162053)),
        ),
        migrations.AlterField(
            model_name='group',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 1, 10, 51, 12, 161051)),
        ),
        migrations.AlterField(
            model_name='group_bookmark',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 1, 10, 51, 12, 162053)),
        ),
        migrations.AlterField(
            model_name='practice',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 1, 10, 51, 12, 164053)),
        ),
        migrations.AlterField(
            model_name='site',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 1, 10, 51, 12, 163051)),
        ),
        migrations.AlterField(
            model_name='user_access',
            name='date_of_access',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 1, 10, 51, 12, 163051)),
        ),
        migrations.AlterField(
            model_name='user_bookmark',
            name='dateAccessed',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 1, 10, 51, 12, 159053)),
        ),
        migrations.AlterField(
            model_name='user_bookmark',
            name='dateAdded',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 1, 10, 51, 12, 159053)),
        ),
    ]
