# Generated by Django 3.2.8 on 2022-01-03 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ra', '0002_alter_usersite_access_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_login',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
