# Generated by Django 3.2.6 on 2021-11-19 15:59

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ra', '0002_auto_20211119_2357'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group_bookmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(default=datetime.datetime(2021, 11, 19, 23, 59, 15, 999292))),
                ('is_trash', models.IntegerField(default=0)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Group_bookmark',
            },
        ),
        migrations.AlterField(
            model_name='group',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 19, 23, 59, 15, 999292)),
        ),
        migrations.AlterField(
            model_name='practice',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 19, 23, 59, 16, 2292)),
        ),
        migrations.AlterField(
            model_name='site',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 19, 23, 59, 16, 292)),
        ),
        migrations.AlterField(
            model_name='user_access',
            name='date_of_access',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 19, 23, 59, 16, 1292)),
        ),
        migrations.AlterField(
            model_name='user_bookmark',
            name='dateAccessed',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 19, 23, 59, 15, 997293)),
        ),
        migrations.AlterField(
            model_name='user_bookmark',
            name='dateAdded',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 19, 23, 59, 15, 997293)),
        ),
        migrations.AlterField(
            model_name='user_folder',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 19, 23, 59, 15, 999292)),
        ),
        migrations.DeleteModel(
            name='Group_bookmarks',
        ),
        migrations.AddField(
            model_name='group_bookmark',
            name='bookmark',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ra.user_bookmark'),
        ),
        migrations.AddField(
            model_name='group_bookmark',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ra.group'),
        ),
    ]
