# Generated by Django 3.1.1 on 2021-08-12 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ra', '0002_auto_20210812_1342'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proxies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proxy', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Proxies',
            },
        ),
    ]
