# Generated by Django 3.2.8 on 2022-01-21 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ra', '0002_alter_bookmark_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='student_id',
        ),
    ]
