# Generated by Django 3.2.8 on 2021-12-01 18:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ra', '0002_auto_20211202_0113'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_bookmark',
            name='folders',
            field=models.ManyToManyField(blank=True, related_name='bookmarks', to='ra.Folder'),
        ),
        migrations.AlterField(
            model_name='practice',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 1, 18, 11, 0, 153433, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='Bookmark_folder',
        ),
    ]
