# Generated by Django 3.1.3 on 2020-12-13 09:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ra', '0002_auto_20201213_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citations',
            name='pubdate',
            field=models.DateField(default=datetime.datetime(2020, 12, 13, 17, 42, 14, 749587)),
        ),
    ]
