# Generated by Django 3.2.6 on 2021-11-26 14:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ra', '0002_auto_20211126_1715'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='User_group',
        ),
        migrations.AlterField(
            model_name='practice',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 26, 14, 58, 57, 253782, tzinfo=utc)),
        ),
        migrations.AlterModelTable(
            name='user_group',
            table='User_group',
        ),
    ]
