# Generated by Django 3.2.6 on 2021-11-01 14:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ra', '0002_auto_20211028_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='Headers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scienceDirect', models.CharField(max_length=5000)),
            ],
            options={
                'db_table': 'Headers',
            },
        ),
        migrations.AlterField(
            model_name='bookmarks',
            name='dateAdded',
            field=models.DateField(default=datetime.datetime(2021, 11, 1, 22, 1, 43, 113859)),
        ),
    ]
