# Generated by Django 3.1.3 on 2021-10-27 03:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ra', '0002_auto_20211027_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmarks',
            name='dateAdded',
            field=models.DateField(default=datetime.datetime(2021, 10, 27, 11, 30, 36, 514565)),
        ),
    ]
