# Generated by Django 3.2.8 on 2022-01-23 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ra', '0002_siteexception'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteexception',
            name='link',
            field=models.CharField(default=1, max_length=2000),
            preserve_default=False,
        ),
    ]
