# Generated by Django 3.2.8 on 2021-12-12 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ra', '0002_auto_20211212_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark_detail',
            name='volume',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
