# Generated by Django 3.2.8 on 2021-12-15 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ra', '0002_auto_20211215_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='student_id',
            field=models.CharField(default='', max_length=50),
        ),
    ]
