# Generated by Django 3.2.6 on 2021-11-15 16:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ra', '0002_auto_20211115_1942'),
    ]

    operations = [
       
        migrations.AlterField(
            model_name='bookmarks',
            name='DOI',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='bookmarks',
            name='ISSN',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='bookmarks',
            name='dateAccessed',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 16, 0, 17, 42, 533062)),
        ),
        migrations.AlterField(
            model_name='bookmarks',
            name='dateAdded',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 16, 0, 17, 42, 533062)),
        ),
        migrations.AlterField(
            model_name='practice',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 16, 0, 17, 42, 535061)),
        ),
    ]
