# Generated by Django 3.2.6 on 2021-11-07 16:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ra', '0002_auto_20211107_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmarks',
            name='dateAccessed',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 8, 0, 24, 53, 491581)),
        ),
        migrations.AlterField(
            model_name='bookmarks',
            name='dateAdded',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 8, 0, 24, 53, 491581)),
        ),
        migrations.AlterField(
            model_name='practice',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 8, 0, 24, 53, 492584)),
        ),
    ]
