# Generated by Django 3.2.8 on 2022-01-21 10:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ra', '0003_remove_user_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='dissertation',
            name='date_published',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dissertation',
            name='file',
            field=models.FileField(default=1, upload_to='media'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dissertation',
            name='num_of_access',
            field=models.IntegerField(default=0),
        ),
    ]
