# Generated by Django 3.1.3 on 2020-12-14 03:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ra', '0003_auto_20201213_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citations',
            name='pubdate',
            field=models.DateField(default=datetime.datetime(2020, 12, 14, 11, 28, 58, 189911)),
        ),
    ]
