# Generated by Django 3.1.1 on 2021-08-12 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ra', '0003_proxies'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxies',
            name='isUsed',
            field=models.IntegerField(default=0),
        ),
    ]
