# Generated by Django 3.1.3 on 2021-10-27 03:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ra', '0003_auto_20211027_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmarks',
            name='dateAdded',
            field=models.DateField(default=datetime.datetime(2021, 10, 27, 11, 53, 0, 595583)),
        ),
    ]
