# Generated by Django 3.2.8 on 2021-12-15 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ra', '0003_department_student_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='student_id',
        ),
        migrations.AddField(
            model_name='user',
            name='student_id',
            field=models.CharField(default='', max_length=50),
        ),
    ]
