# Generated by Django 3.2.8 on 2022-01-03 06:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ra', '0003_alter_user_login_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_login',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
