# Generated by Django 3.2.6 on 2021-11-19 16:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ra', '0003_auto_20211119_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 20, 0, 5, 52, 87991)),
        ),
        migrations.AlterField(
            model_name='group_bookmark',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 20, 0, 5, 52, 88992)),
        ),
        migrations.AlterField(
            model_name='practice',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 20, 0, 5, 52, 91994)),
        ),
        migrations.AlterField(
            model_name='site',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 20, 0, 5, 52, 89993)),
        ),
        migrations.AlterField(
            model_name='user_access',
            name='date_of_access',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 20, 0, 5, 52, 90993)),
        ),
        migrations.AlterField(
            model_name='user_bookmark',
            name='dateAccessed',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 20, 0, 5, 52, 86994)),
        ),
        migrations.AlterField(
            model_name='user_bookmark',
            name='dateAdded',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 20, 0, 5, 52, 86994)),
        ),
        migrations.AlterField(
            model_name='user_folder',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 20, 0, 5, 52, 88992)),
        ),
        migrations.AlterModelTable(
            name='user_bookmark',
            table='User_bookmark',
        ),
    ]
