# Generated by Django 3.2.6 on 2021-11-01 14:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ra', '0003_auto_20211101_2201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='headers',
            old_name='scienceDirect',
            new_name='text',
        ),
        migrations.AlterField(
            model_name='bookmarks',
            name='dateAdded',
            field=models.DateField(default=datetime.datetime(2021, 11, 1, 22, 5, 12, 274571)),
        ),
    ]
