# Generated by Django 3.2.8 on 2021-12-05 13:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ra', '0004_auto_20211203_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_bookmark',
            name='keyword',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='practice',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
