# Generated by Django 3.2.8 on 2022-01-24 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ra', '0004_auto_20220123_1902'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Site_exception',
        ),
    ]
