# Generated by Django 3.2.8 on 2021-12-20 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ra', '0004_auto_20211215_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='student_id',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
    ]
