# Generated by Django 3.2.8 on 2021-12-23 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ra', '0006_user_is_login'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_access',
            new_name='UserSite_access',
        ),
        migrations.AddField(
            model_name='site',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterModelTable(
            name='usersite_access',
            table='UserSite_access',
        ),
        migrations.CreateModel(
            name='User_login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
