# Generated by Django 3.2.8 on 2021-12-23 13:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ra', '0007_auto_20211223_2139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_login',
        ),
        migrations.AlterField(
            model_name='user_login',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
