# Generated by Django 3.2.8 on 2021-12-23 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ra', '0008_auto_20211223_2156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersite_access',
            name='department',
        ),
    ]
